#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

function usage_exit() {
    local command_name=$(basename "$0")
    echo "Usage: $command_name file" >&2
    exit $1
}

while getopts :h opt; do
    case $opt in
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit 2
fi

if [ -f "$1" ]; then

    file_name=$(basename "$1")

    # ウィンドウのタイトルにファイル名の文字列を含むものがあればポップアップする
    if winactivate "$file_name"; then
        exit 0
    fi
fi

cygstart -- "$1"
