#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

function usage_exit() {
    local command_name=$(basename "$0")
    echo "Usage: $command_name file" >&2
    exit 1
}

if getopts : opt; then
    usage_exit
fi

# オプションに -- が指定されたときに $# を１マイナスする
# -- は、- で始まるファイルを利用する場合に必要なオプション
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit
fi

if [ -f "$1" ]; then

    file_name=$(basename "$1")

    # ウィンドウのタイトルにファイル名の文字列を含むものがあればポップアップする
    if winactivate "$file_name"; then
        exit 0
    fi
fi

cygstart -- "$1"
